name: pomatez
adopt-info: pomatez

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  pomatez:
    command: desktop-launch $SNAP/app/electron/pomatez --no-sandbox
    extensions: [gnome-3-28]
    plugs:
      - audio-playback
      - desktop
      - desktop-legacy
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1

parts:
  pomatez:
    source: app/electron
    plugin: nodejs
    nodejs-version: 12.18.1

    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
      - libglu1-mesa

    override-pull: |
      snapcraftctl pull
      version="$(git describe --abbrev=0 --always)"
      snapcraftctl set-version "$version"

    override-build: |
      snapcraftctl build
      rm -rf $SNAPCRAFT_PART_INSTALL/app/electron
      mkdir -p $SNAPCRAFT_PART_INSTALL/app/electron
      mv dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/app/electron
    prime:
      - -node_modules
