name: Release
on:
  push:
    branches:
      - master
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
    outputs:
      tag: ${{ steps.release.outputs.tag_name }}
      release_created: ${{ steps.release.outputs.release_created }}
      sha: ${{ steps.release.outputs.sha }}
      upload_url: ${{ steps.release.outputs.upload_url }}
  build-node:
    name: "Build Node"
    needs: release-please
    if: needs.release-please.outputs.release_created
    uses: ./.github/workflows/build.yml
  build-tauri:
    name: "Build Tauri"
    needs: release-please
    if: needs.release-please.outputs.release_created
    uses: ./.github/workflows/build-tauri.yml
  publish:
    name: Publish
    needs:
      - build-node
      - build-tauri
      - release-please
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
      - name: Upload Release Assets
        id: upload-release-asset
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.release-please.outputs.tag }}
          files: |
            built-*/latest*
            built-*/*.deb
            built-*/*.rpm
            built-*/*.dmg
            built-*/*.AppImage
            built-*/*.zip
            built-*/*.exe
            built-*/*.snap
            built-*/*.blockmap
  publish-to-homebrew-cask:
    name: Publish to Homebrew Cask
    needs:
      - publish
      - release-please
    runs-on: macos-latest
    steps:
      - uses: Homebrew/actions/bump-packages@master
        with:
          casks: pomatez
          token: ${{ secrets.GITHUB_TOKEN }}
  publish-to-winget:
    name: Publish to WinGet
    needs:
      - publish
      - release-please
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: Zidoro.Pomatez
          installers-regex: 'setup\.exe$'
          max-versions-to-keep: 5 # keep only latest 5 versions
          release-tag: ${{ needs.release-please.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}