name: Release
on:
  push:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
jobs:
  build-node:
    name: "Build Node"
    uses: ./.github/workflows/build.yml
  build-tauri:
    name: "Build Tauri"
    uses: ./.github/workflows/build-tauri.yml
    secrets: inherit
  publish:
    name: Publish
    needs:
      - build-node
      - build-tauri
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        shell: bash
        run: ls -R

